apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote
spec:
  type: NodePort
  selector:
    app: vote-deployment
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - nodePort: 31000
      port: 5000
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)