apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ic-datacenter
  name: ic-deploy-datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-datacenter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ic-datacenter
    spec:
      containers:
      - image: debian:latest
        name: ic-main-datacenter
        command: ['/bin/bash', '-c', 'while true; do cat /ic/blog; sleep 5; done']
        volumeMounts:
        - mountPath: /ic
          name: ic-volume-datacenter
      initContainers:
      - name: ic-msg-datacenter
        image: debian:latest
        command: ['/bin/bash', '-c', 'echo Init Done - Welcome to xFusionCorp Industries > /ic/blog']
        volumeMounts:
        - mountPath: /ic
          name: ic-volume-datacenter
      volumes:
      - emptyDir: {}
        name: ic-volume-datacenter
status: {}